"""Write the analytical model as a self-contained, runnable PyNite script.

The file imports **only PyNite and the standard library** — no ``typehaus`` — so a PE can
drop it into their own environment, read every number in it, change one and re-run. The
model is embedded as literal data taken from ``PyniteInputs``, the same call list
``analytical/solve.py`` runs in process; a script that built a different model from the
solve beside it would be the drift this whole package exists to prevent.

Byte-deterministic: no timestamp, no path, everything already sorted by ``build_inputs``.
"""

from __future__ import annotations

from pathlib import Path

from typehaus.analytical.graph import AnalyticalModel
from typehaus.analytical.pynite_map import (
    N_TO_LB,
    NM_TO_LB_IN,
    PyniteInputs,
    build_inputs,
)

_INDENT = "    "


def write_pynite_script(model: AnalyticalModel, path: Path) -> Path:
    inputs = build_inputs(model)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(_lines(model, inputs)) + "\n", encoding="utf-8", newline="\n")
    return path


def _lines(model: AnalyticalModel, inputs: PyniteInputs) -> list[str]:
    return [
        *_header(model),
        "",
        "from Pynite import FEModel3D",
        "",
        f"N_TO_LB = {N_TO_LB!r}",
        f"NM_TO_LB_IN = {NM_TO_LB_IN!r}",
        "",
        *_data(inputs),
        "",
        *_BUILD,
        "",
        *_REPORT,
        "",
        'if __name__ == "__main__":',
        f"{_INDENT}main()",
        "",
        *_footer(model),
    ]


def _header(model: AnalyticalModel) -> list[str]:
    scope = ", ".join(model.scope) if model.scope else "(none recorded)"
    return [
        '"""Analytical model generated by Type:Haus — do not hand-edit, regenerate it.',
        "",
        "Units: pounds and inches throughout (E in psi, line loads in lb/in, moments lb-in).",
        "Axes:  X, Y, Z with **Z up**, mapped straight through from the model and the IFC.",
        "       PyNite documents itself Y-up but its solver is axis-agnostic; the section",
        "       properties below already account for the local-axis convention that follows",
        "       from Z-up (bending under gravity is about a member's local y-axis, so Iy",
        "       carries the strong-axis value).",
        "Self weight is NOT applied: rho is zero. The dead case is the load the engineering",
        "       records consumed, and adding a second one would disagree with the calc sheet.",
        "",
        f"Scope (engineering items): {scope}",
        '"""',
    ]


def _data(inputs: PyniteInputs) -> list[str]:
    return [
        f"NODES = {_fmt(inputs.nodes)}",
        "",
        f"MATERIALS = {_fmt(inputs.materials)}",
        "",
        f"SECTIONS = {_fmt(inputs.sections)}",
        "",
        f"MEMBERS = {_fmt(inputs.members)}",
        "",
        f"SUPPORTS = {_fmt(inputs.supports)}",
        "",
        f"RELEASES = {_fmt(inputs.releases)}",
        "",
        f"DIST_LOADS = {_fmt(inputs.dist_loads)}",
        "",
        f"POINT_LOADS = {_fmt(inputs.pt_loads)}",
        "",
        f"NODE_LOADS = {_fmt(inputs.node_loads)}",
        "",
        f"COMBOS = {_fmt(inputs.combos)}",
    ]


def _fmt(rows: tuple) -> str:
    """One tuple per line, ``repr``-round-trippable, stable across runs."""
    if not rows:
        return "()"
    body = "".join(f"{_INDENT}{row!r},\n" for row in rows)
    return f"(\n{body})"


# Mirrors ``analytical/solve.py::_assemble`` call for call.
_BUILD = (
    "def build():",
    f"{_INDENT}model = FEModel3D()",
    f"{_INDENT}for name, x, y, z in NODES:",
    f"{_INDENT * 2}model.add_node(name, x, y, z)",
    f"{_INDENT}for name, e, g, nu, rho in MATERIALS:",
    f"{_INDENT * 2}model.add_material(name, e, g, nu, rho)",
    f"{_INDENT}for name, a, iy, iz, j in SECTIONS:",
    f"{_INDENT * 2}model.add_section(name, a, iy, iz, j)",
    f"{_INDENT}for name, i_node, j_node, material, section, rotation in MEMBERS:",
    f"{_INDENT * 2}model.add_member(name, i_node, j_node, material, section, rotation=rotation)",
    f"{_INDENT}for name, flags in RELEASES:",
    f"{_INDENT * 2}model.def_releases(name, *flags)",
    f"{_INDENT}for node, dx, dy, dz, rx, ry, rz in SUPPORTS:",
    f"{_INDENT * 2}model.def_support(node, dx, dy, dz, rx, ry, rz)",
    f"{_INDENT}for member, direction, w1, w2, x1, x2, case in DIST_LOADS:",
    f"{_INDENT * 2}model.add_member_dist_load(member, direction, w1, w2, x1, x2, case=case)",
    f"{_INDENT}for member, direction, p, x, case in POINT_LOADS:",
    f"{_INDENT * 2}model.add_member_pt_load(member, direction, p, x, case=case)",
    f"{_INDENT}for node, direction, p, case in NODE_LOADS:",
    f"{_INDENT * 2}model.add_node_load(node, direction, p, case=case)",
    f"{_INDENT}for name, factors in COMBOS:",
    f"{_INDENT * 2}model.add_load_combo(name, dict(factors))",
    f"{_INDENT}return model",
)

_REPORT = (
    "def main():",
    f"{_INDENT}model = build()",
    f"{_INDENT}model.analyze_linear(log=False, check_stability=True, sparse=True)",
    f"{_INDENT}for combo, _ in COMBOS:",
    f'{_INDENT * 2}print("")',
    f'{_INDENT * 2}print("== REACTIONS  combo %s  (lb, lb-in; SI on the next line)" % combo)',
    f'{_INDENT * 2}print("%-20s %12s %12s %12s %12s %12s %12s"',
    f'{_INDENT * 6}% ("node", "FX", "FY", "FZ", "MX", "MY", "MZ"))',
    f"{_INDENT * 2}for name, dx, dy, dz, rx, ry, rz in SUPPORTS:",
    f"{_INDENT * 3}node = model.nodes[name]",
    f"{_INDENT * 3}values = (node.RxnFX[combo], node.RxnFY[combo], node.RxnFZ[combo],",
    f"{_INDENT * 5}node.RxnMX[combo], node.RxnMY[combo], node.RxnMZ[combo])",
    f'{_INDENT * 3}print("%-20s %12.3f %12.3f %12.3f %12.3f %12.3f %12.3f"',
    f"{_INDENT * 7}% ((name,) + tuple(float(v) for v in values)))",
    f"{_INDENT * 3}si = tuple(float(v) / N_TO_LB for v in values[:3])",
    f"{_INDENT * 3}si = si + tuple(float(v) / NM_TO_LB_IN for v in values[3:])",
    f'{_INDENT * 3}print("SI  %-16s %12.3f %12.3f %12.3f %12.3f %12.3f %12.3f"',
    f"{_INDENT * 7}% ((name,) + si))",
    f'{_INDENT * 2}print("-- MEMBER EXTREMES  combo %s" % combo)',
    f'{_INDENT * 2}print("%-24s %14s %14s %14s"',
    f'{_INDENT * 6}% ("member", "max|M| lb-in", "max|V| lb", "axial lb"))',
    f"{_INDENT * 2}for name, i_node, j_node, material, section, rotation in MEMBERS:",
    f"{_INDENT * 3}member = model.members[name]",
    f"{_INDENT * 3}moment = max(abs(float(getter(axis, combo)))",
    f"{_INDENT * 6}for getter in (member.max_moment, member.min_moment)",
    f'{_INDENT * 6}for axis in ("My", "Mz"))',
    f"{_INDENT * 3}shear = max(abs(float(getter(axis, combo)))",
    f"{_INDENT * 5}for getter in (member.max_shear, member.min_shear)",
    f'{_INDENT * 5}for axis in ("Fy", "Fz"))',
    f"{_INDENT * 3}hi = float(member.max_axial(combo))",
    f"{_INDENT * 3}lo = float(member.min_axial(combo))",
    f"{_INDENT * 3}axial = hi if abs(hi) >= abs(lo) else lo",
    f'{_INDENT * 3}print("%-24s %14.3f %14.3f %14.3f" % (name, moment, shear, axial))',
)


def _footer(model: AnalyticalModel) -> list[str]:
    """The claims a reviewer is entitled to reject, and what the model does not carry."""
    lines = ["# ---------------------------------------------------------------------------"]
    lines += ["# ASSUMPTIONS"]
    lines += [f"#   - {line}" for line in model.assumptions] or ["#   (none recorded)"]
    lines += ["# GAPS — what this model does NOT carry"]
    lines += [f"#   - {line}" for line in model.gaps] or ["#   (none recorded)"]
    lines += ["# ---------------------------------------------------------------------------"]
    return lines
