"""``engineering.toml.draft`` — the seal register as a form, generated for a person to fill.

**This does not weaken decision #65.** The engine still never writes
``houses/<name>/engineering.toml``. It writes a *draft*, into ``out/``, with every field a
person must supply left as a visible blank — and ``register.py`` refuses to load a file
that still holds one. Copying the draft over the real file is a deliberate act by the
owner, after a PE has actually stamped something, and that act is the seal.

What the scaffold saves is the mechanical half: which items exist, what each one's scope
sentence is, and above all the FINGERPRINT of each, which a person otherwise has to obtain
one at a time with ``haus engineering --fingerprint`` and paste without transcription
error. Forty items is forty chances to fat-finger a hex string into a stamp that then reads
FRESH against nothing.

**One block per kind**, not per item. A PE stamps a *scope* — "the retaining walls", "the
deck posts and their footings" — and one seal covering seven walls is how the profession
works; ``register.py`` already allows exactly that. A per-item scaffold would invite forty
separate stamps, which is both wrong and expensive.

Three shapes, and the difference is whether it is honest to pre-fill anything:

* **OK** — every state graded and under 1. Full block, uncommented, all fingerprints.
* **INCOMPLETE** — computed, but an input is missing. The block is present and uncommented,
  headed by the union of what is missing, because a PE may well be the person who supplies
  it; the fingerprints are populated so the stamp pins the model it was made against.
* **NO_CALC / OVER** — deferred to somebody else's design, or over capacity. The block is
  written out entirely COMMENTED, with the deferral's designer and deliverable and no
  fingerprint at all: there is nothing to pin, and an unpinned seal never satisfies
  ``--require-seal``.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from typehaus.engineering.fingerprint import fingerprint
from typehaus.engineering.item import EngineeringRecord, Status

#: What a person must replace. ``register.PLACEHOLDER`` is the pair the loader refuses on.
ENGINEER = "<<ENGINEER NAME, PE>>"
LICENSE = "<<STATE 00000>>"
SEALED_ON = "<<YYYY-MM-DD>>"
DOCUMENT = "<<path/to/sealed.pdf>>"

_HEADER = """\
# THIS FILE IS NOT A SEAL.
#
# It is a form, generated by `haus handoff` from the engineering register as it stood at
# the moment below. Every field written as <<LIKE THIS>> is a blank a person has to fill
# in, and `typehaus/engineering/register.py` REFUSES to load a file that still holds one —
# so this cannot become a seal by being copied.
#
# To use it:
#   1. A licensed professional reviews `calcs.pdf` in this bundle and stamps it.
#   2. Fill in the engineer, the license, the date and the path to the stamped document,
#      for the blocks they actually sealed. DELETE the blocks they did not.
#   3. Copy this file to `houses/{house}/engineering.toml`.
#   4. Run `haus engineering --require-seal` and `haus print --sealed`.
#
# The fingerprints below are already filled in and MUST NOT be edited. Each pins a seal to
# the exact inputs its calculation consumed; leave one out and the item reads "stamped, not
# pinned", which never satisfies the final gate. If the model changes after the stamp, the
# fingerprint stops matching and the item reads STALE — which is the whole point.
#
# One [[signoff]] per kind, because a professional stamps a scope and not a line item. Split
# a block if the work was split between two people; every item must appear in exactly one.
#
# Generated: {generated}
# Engine:    {engine_version}
# Model:     {content_hash}
"""


def scaffold_register(records: Iterable[EngineeringRecord], *, house: str, generated: str,
                      engine_version: str, content_hash: str) -> str:
    """Render the draft register. Pure — the caller decides where it lands."""
    by_kind: dict[str, list[EngineeringRecord]] = {}
    for record in records:
        by_kind.setdefault(record.kind, []).append(record)

    blocks = [_block(kind, sorted(group, key=lambda r: r.item_id))
              for kind, group in sorted(by_kind.items())]
    header = _HEADER.format(house=house, generated=generated,
                            engine_version=engine_version, content_hash=content_hash)
    return header + "\n" + "\n".join(blocks)


def _block(kind: str, records: Sequence[EngineeringRecord]) -> str:
    statuses = {record.status for record in records}
    if statuses <= {Status.NO_CALC} or Status.OVER in statuses:
        return _deferred_block(kind, records)
    lines = [f"# --- {kind} ({len(records)} item(s)) " + "-" * max(1, 56 - len(kind))]
    missing = sorted({text for record in records for text in record.missing})
    if missing:
        lines.append("#")
        lines.append("# INCOMPLETE — do not seal until:")
        lines.extend(f"#   - {text}" for text in missing)
    lines.append("")
    lines.extend(_signoff_lines(kind, records))
    return "\n".join(lines) + "\n"


def _deferred_block(kind: str, records: Sequence[EngineeringRecord]) -> str:
    """A kind this engine computes nothing for: commented out, and it says who owns it."""
    from typehaus.engineering.deferred import DEFERRALS

    deferral = DEFERRALS.get(kind)
    over = [record for record in records if record.status is Status.OVER]
    lines = [f"# --- {kind} ({len(records)} item(s)) " + "-" * max(1, 56 - len(kind)), "#"]
    if over:
        lines.append("# OVER CAPACITY — this engine computed these and they do not pass. A")
        lines.append("# seal over them would be a seal over a failure; fix the design first.")
        lines.extend(f"#   {record.item_id}: {record.describe()}" for record in over)
    else:
        lines.append("# DEFERRED — this engine computes nothing here, by decision, so there")
        lines.append("# is nothing to fingerprint and a seal recorded below could not be")
        lines.append("# pinned. Left entirely commented out on purpose.")
        if deferral is not None:
            lines.append(f"#   designer:    {deferral.designer}")
            lines.append(f"#   deliverable: {deferral.deliverable}")
            lines.append(f"#   unblocks:    {deferral.unblocks}")
    lines.append("#")
    lines.extend("# " + line if line else "#"
                 for line in _signoff_lines(kind, records, pin=False))
    return "\n".join(lines) + "\n"


def _signoff_lines(kind: str, records: Sequence[EngineeringRecord],
                   *, pin: bool = True) -> list[str]:
    scope = _scope(kind, records)
    lines = [
        "[[signoff]]",
        f'id = "{kind}"',
        f'scope = "{_escape(scope)}"',
        f'engineer = "{ENGINEER}"',
        f'license = "{LICENSE}"',
        f'sealed_on = "{SEALED_ON}"',
        f'document = "{DOCUMENT}"',
        "covers = [",
    ]
    lines.extend(f'    "{record.item_id}",' for record in records)
    lines.append("]")
    if pin:
        lines.append("")
        lines.append("[signoff.fingerprint]  # computed — do not edit")
        for record in records:
            lines.append(f'"{record.item_id}" = "{fingerprint(record)}"')
    lines.append("")
    return lines


def _scope(kind: str, records: Sequence[EngineeringRecord]) -> str:
    """The sentence a reviewer reads first: what this stamp is over, in the calc's own terms."""
    basis = next((record.basis for record in records if record.basis), "")
    subject = f"{len(records)} {kind.replace('_', ' ')} item(s)"
    return f"{subject}" + (f" — {basis}" if basis else "")


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')
