"""Round-trip export/import for cross-machine ship (U11)."""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest

from typehaus.source.bundle import (
    MANIFEST_NAME,
    ImportResult,
    export_house,
    import_house,
)


def _write_house_with_external_underlay(root: Path) -> Path:
    """A minimal house whose underlay lives two levels up, like houses/catlin."""
    reference = root / "reference_drawings"
    reference.mkdir(parents=True)
    (reference / "floor 1.png").write_bytes(b"PNG-BYTES-1")
    house = root / "houses" / "demo"
    (house / "plan").mkdir(parents=True)
    (house / "plan" / "manifest.py").write_text("# haus: editable\nHOUSE = 'demo'\n")
    (house / "preferences.toml").write_text(
        "[units]\nsystem = \"imperial\"\n\n"
        "[[underlay]]\n"
        'path = "../../reference_drawings/floor 1.png"\n'
        'storey = "main"\n'
        "origin_x_m = 0.0\norigin_y_m = 0.0\n"
        "width_m = 10.0\nheight_m = 12.0\nopacity = 0.2\n"
    )
    # Generated byproducts that must not travel.
    (house / "out").mkdir()
    (house / "out" / "model.json").write_text("{}")
    (house / "plan" / "__pycache__").mkdir()
    (house / "plan" / "__pycache__" / "manifest.cpython-39.pyc").write_bytes(b"\x00")
    return house


def test_export_relinks_external_underlay_and_excludes_byproducts(tmp_path: Path) -> None:
    house = _write_house_with_external_underlay(tmp_path)
    original_prefs = (house / "preferences.toml").read_text()

    result = export_house(house, tmp_path / "demo.haus.zip")
    assert result.archive.is_file()
    assert result.relinked_underlays  # the external png was relinked
    assert not result.missing_underlays
    # Source house is never mutated.
    assert (house / "preferences.toml").read_text() == original_prefs

    with zipfile.ZipFile(result.archive) as archive:
        names = archive.namelist()
        manifest = json.loads(archive.read(MANIFEST_NAME))
        prefs = archive.read("house/preferences.toml").decode()
    assert MANIFEST_NAME in names
    assert "house/underlays/floor 1.png" in names
    assert "house/plan/manifest.py" in names
    # Byproducts excluded.
    assert not any("out/model.json" in n for n in names)
    assert not any(".pyc" in n for n in names)
    # Rewritten to a house-local relative path (no '..').
    assert 'path = "underlays/floor 1.png"' in prefs
    assert "../../" not in prefs
    assert manifest["name"] == "demo"
    assert manifest["relinked_underlays"][0]["to"] == "underlays/floor 1.png"


def test_import_round_trips_and_resolves_underlay(tmp_path: Path) -> None:
    house = _write_house_with_external_underlay(tmp_path)
    archive = export_house(house, tmp_path / "demo.haus.zip").archive

    dest = tmp_path / "imported"
    result = import_house(archive, dest)
    assert isinstance(result, ImportResult)
    assert result.ok
    assert result.name == "demo"
    # The underlay now lives inside the imported house and resolves.
    assert (dest / "underlays" / "floor 1.png").read_bytes() == b"PNG-BYTES-1"
    assert (dest / "plan" / "manifest.py").is_file()
    assert not result.missing_underlays and not result.missing_assets


def test_export_bundles_house_local_placeable_and_furniture_assets(tmp_path: Path) -> None:
    house = tmp_path / "houses" / "furnished"
    (house / "plan").mkdir(parents=True)
    (house / "preferences.toml").write_text("[units]\nsystem = \"imperial\"\n")
    (house / "assets" / "placeables").mkdir(parents=True)
    (house / "assets" / "placeables" / "abc.glb").write_bytes(b"GLB")
    (house / "assets" / "placeables.json").write_text(json.dumps({
        "revision": 1,
        "types": [{"tag": "F-CHAIR", "model": "assets/placeables/abc.glb", "plan_svg": None}],
    }))
    (house / "furniture" / "meshes").mkdir(parents=True)
    (house / "furniture" / "meshes" / "SOFA.glb").write_bytes(b"MESH")
    (house / "furniture" / "imports.json").write_text(json.dumps({
        "types": [{"tag": "FURN-SOFA", "mesh": "furniture/meshes/SOFA.glb"}],
        "instances": [],
    }))

    archive = export_house(house, tmp_path / "furnished.haus.zip").archive
    dest = tmp_path / "imported"
    result = import_house(archive, dest)
    assert result.ok
    assert (dest / "assets" / "placeables" / "abc.glb").read_bytes() == b"GLB"
    assert (dest / "furniture" / "meshes" / "SOFA.glb").read_bytes() == b"MESH"


def test_import_reports_missing_asset_reference(tmp_path: Path) -> None:
    house = tmp_path / "houses" / "broken"
    (house / "assets").mkdir(parents=True)
    (house / "preferences.toml").write_text("[units]\nsystem = \"imperial\"\n")
    (house / "assets" / "placeables.json").write_text(json.dumps({
        "types": [{"tag": "F-GHOST", "model": "assets/placeables/missing.glb", "plan_svg": None}],
    }))
    archive = export_house(house, tmp_path / "broken.haus.zip").archive
    result = import_house(archive, tmp_path / "imported")
    assert not result.ok
    assert any("missing.glb" in ref for ref in result.missing_assets)


def test_import_rejects_zip_slip(tmp_path: Path) -> None:
    evil = tmp_path / "evil.zip"
    with zipfile.ZipFile(evil, "w") as archive:
        archive.writestr(MANIFEST_NAME, json.dumps({"name": "evil"}))
        archive.writestr("house/../escape.txt", "pwned")
    with pytest.raises(ValueError, match="escapes destination"):
        import_house(evil, tmp_path / "dest")


def test_import_refuses_nonempty_destination_without_force(tmp_path: Path) -> None:
    house = tmp_path / "houses" / "demo"
    (house / "plan").mkdir(parents=True)
    (house / "preferences.toml").write_text("[units]\nsystem = \"imperial\"\n")
    archive = export_house(house, tmp_path / "demo.haus.zip").archive
    dest = tmp_path / "dest"
    dest.mkdir()
    (dest / "existing.txt").write_text("keep me")
    with pytest.raises(ValueError, match="not empty"):
        import_house(archive, dest)
    # force overwrites.
    result = import_house(archive, dest, force=True)
    assert result.house_dir == dest.resolve()


def test_catlin_round_trip_builds_identically(tmp_path: Path) -> None:
    """Export the real house, import to a fresh dir, and confirm it resolves the same."""
    from typehaus.resolve import resolve
    from typehaus.source import load_plan

    repo_root = Path(__file__).resolve().parents[3]
    catlin = repo_root / "houses" / "catlin"
    if not catlin.is_dir():
        pytest.skip("catlin house not present in this checkout")

    export = export_house(catlin, tmp_path / "catlin.haus.zip")
    assert not export.missing_underlays
    assert export.relinked_underlays  # catlin references ../../catlin_floorplan/*.png

    dest = tmp_path / "catlin-import"
    result = import_house(export.archive, dest)
    assert result.ok, (result.missing_underlays, result.missing_assets)

    baseline = load_plan(catlin)
    imported = load_plan(dest)
    assert baseline.plan is not None and imported.plan is not None
    base_model, base_findings = resolve(baseline.plan)
    imp_model, imp_findings = resolve(imported.plan)
    base_errors = [f for f in base_findings if f.severity.value == "error"]
    imp_errors = [f for f in imp_findings if f.severity.value == "error"]
    assert imp_errors == base_errors
    # Same resolved geometry counts — the import is a faithful copy.
    assert len(imp_model.walls) == len(base_model.walls)
    assert len(list(imp_model.all_members())) == len(list(base_model.all_members()))
