"""Portable export/import of a house folder for cross-machine ship (U11).

A house is a self-describing folder (``plan/``, ``preferences.toml``, and optional
``assets/``/``furniture/`` catalogs).  Two things stop a plain folder copy from being
portable:

* **Reference underlays.**  ``preferences.toml`` may point at calibration drawings that live
  *outside* the house folder (the Catlin house references ``../../catlin_floorplan/*.png``).
  Export copies those files into a house-local ``underlays/`` directory and rewrites the
  ``path`` so the imported house resolves them wherever it lands.
* **Generated byproducts.**  ``out/`` and ``__pycache__`` are machine-local build output; they
  are excluded so the archive carries only source + bundled assets.

Imported/house-local placeable GLBs and furniture meshes already use house-relative paths, so
they travel unmodified.  Export never mutates the source house — all rewriting happens on a copy
inside the archive.
"""

from __future__ import annotations

import json
import shutil
import time
import zipfile
from dataclasses import dataclass
from pathlib import Path

from typehaus._meta import engine_version

MANIFEST_NAME = "typehaus_export.json"
BUNDLE_PREFIX = "house"
BUNDLED_UNDERLAY_DIR = "underlays"

_EXCLUDE_DIRS = {"out", "__pycache__", ".git", ".pytest_cache", ".mypy_cache"}
_EXCLUDE_SUFFIXES = {".pyc", ".pyo"}
_EXCLUDE_NAMES = {".DS_Store"}


@dataclass
class ExportResult:
    archive: Path
    name: str
    relinked_underlays: tuple[tuple[str, str], ...] = ()
    missing_underlays: tuple[str, ...] = ()
    file_count: int = 0


@dataclass
class ImportResult:
    house_dir: Path
    name: str
    missing_underlays: tuple[str, ...] = ()
    missing_assets: tuple[str, ...] = ()

    @property
    def ok(self) -> bool:
        return not self.missing_underlays and not self.missing_assets


def _is_excluded_dir(name: str) -> bool:
    return name in _EXCLUDE_DIRS


def _is_excluded_file(path: Path) -> bool:
    return path.name in _EXCLUDE_NAMES or path.suffix.lower() in _EXCLUDE_SUFFIXES


def _iter_house_files(house_dir: Path):
    """Yield ``(absolute_path, relative_posix)`` for every portable source file."""
    for path in sorted(house_dir.rglob("*")):
        if path.is_dir():
            continue
        relative = path.relative_to(house_dir)
        if any(_is_excluded_dir(part) for part in relative.parts[:-1]):
            continue
        if _is_excluded_file(path):
            continue
        yield path, relative.as_posix()


def _looks_like_house(house_dir: Path) -> bool:
    return (house_dir / "preferences.toml").exists() or (house_dir / "plan").is_dir()


def _external_underlay(house_dir: Path, raw_path: str) -> Path | None:
    """Return the resolved source path when an underlay lives outside the house folder."""
    candidate = (house_dir / raw_path).resolve()
    try:
        candidate.relative_to(house_dir.resolve())
    except ValueError:
        return candidate
    return None


def _underlay_paths(preferences_text: str) -> list[str]:
    """Extract every ``path`` declared under an ``[[underlay]]`` table, in file order."""
    paths: list[str] = []
    in_underlay = False
    for line in preferences_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            in_underlay = stripped == "[[underlay]]"
            continue
        if in_underlay and stripped.startswith("path") and "=" in stripped:
            _, _, value = stripped.partition("=")
            paths.append(value.strip().strip('"').strip("'"))
    return paths


def _rewrite_underlay_paths(preferences_text: str, mapping: dict[str, str]) -> str:
    """Replace ``path = "old"`` lines inside ``[[underlay]]`` tables using ``mapping``."""
    if not mapping:
        return preferences_text
    out: list[str] = []
    in_underlay = False
    for line in preferences_text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("["):
            in_underlay = stripped == "[[underlay]]"
            out.append(line)
            continue
        if in_underlay and stripped.startswith("path") and "=" in stripped:
            current = stripped.split("=", 1)[1].strip().strip('"').strip("'")
            if current in mapping:
                newline = "\n" if line.endswith("\n") else ""
                out.append(f'path = "{mapping[current]}"{newline}')
                continue
        out.append(line)
    return "".join(out)


def _unique_name(used: set[str], filename: str) -> str:
    """Pick a collision-free bundled filename, preserving the extension."""
    candidate = filename
    if candidate not in used:
        used.add(candidate)
        return candidate
    stem = Path(filename).stem
    suffix = Path(filename).suffix
    index = 1
    while f"{stem}-{index}{suffix}" in used:
        index += 1
    candidate = f"{stem}-{index}{suffix}"
    used.add(candidate)
    return candidate


def _relink_underlays(house_dir: Path, staging: Path) -> tuple[dict[str, str], list[str]]:
    """Copy external underlays into ``staging/underlays`` and return path rewrites.

    Returns ``(mapping, missing)`` where ``mapping`` is original-path → bundled relative path
    for underlays that were relinked, and ``missing`` lists external underlays whose source
    file is absent (their paths are left untouched so the loss is visible, not silent).
    """
    preferences = house_dir / "preferences.toml"
    if not preferences.exists():
        return {}, []
    mapping: dict[str, str] = {}
    missing: list[str] = []
    used_names: set[str] = set()
    underlay_root = staging / BUNDLED_UNDERLAY_DIR
    for raw in _underlay_paths(preferences.read_text()):
        source = _external_underlay(house_dir, raw)
        if source is None:  # already house-local; copied verbatim with the tree
            continue
        if raw in mapping or raw in missing:
            continue
        if not source.is_file():
            missing.append(raw)
            continue
        underlay_root.mkdir(parents=True, exist_ok=True)
        bundled_name = _unique_name(used_names, source.name)
        shutil.copy2(source, underlay_root / bundled_name)
        mapping[raw] = f"{BUNDLED_UNDERLAY_DIR}/{bundled_name}"
    return mapping, missing


def export_house(house_dir: Path, archive_path: Path | None = None) -> ExportResult:
    """Bundle ``house_dir`` and its external reference assets into a portable ``.zip``.

    The source house is never mutated; underlay relinking is applied only to the staged copy.
    """
    house_dir = house_dir.resolve()
    if not house_dir.is_dir() or not _looks_like_house(house_dir):
        raise ValueError(f"not a house folder (needs plan/ or preferences.toml): {house_dir}")
    name = house_dir.name
    if archive_path is None:
        archive_path = Path.cwd() / f"{name}.haus.zip"
    archive_path = archive_path.resolve()
    if archive_path.suffix != ".zip":
        archive_path = archive_path.with_suffix(".zip")

    staging_parent = archive_path.parent / f".{name}.export.staging"
    staging = staging_parent / BUNDLE_PREFIX
    if staging_parent.exists():
        shutil.rmtree(staging_parent)
    staging.mkdir(parents=True)
    try:
        file_count = 0
        for absolute, relative in _iter_house_files(house_dir):
            destination = staging / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(absolute, destination)
            file_count += 1

        mapping, missing = _relink_underlays(house_dir, staging)
        preferences = staging / "preferences.toml"
        if mapping and preferences.exists():
            preferences.write_text(_rewrite_underlay_paths(preferences.read_text(), mapping))

        manifest = {
            "format": "typehaus-house-bundle",
            "format_version": 1,
            "name": name,
            "engine_version": engine_version(),
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "relinked_underlays": [
                {"from": key, "to": value} for key, value in sorted(mapping.items())],
            "missing_underlays": sorted(missing),
        }

        archive_path.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr(MANIFEST_NAME, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
            for path in sorted(staging.rglob("*")):
                if path.is_file():
                    archive.write(path, f"{BUNDLE_PREFIX}/{path.relative_to(staging).as_posix()}")
    finally:
        shutil.rmtree(staging_parent, ignore_errors=True)

    return ExportResult(archive=archive_path, name=name,
                        relinked_underlays=tuple(sorted(mapping.items())),
                        missing_underlays=tuple(sorted(missing)), file_count=file_count)


def _safe_members(archive: zipfile.ZipFile, dest: Path) -> list[str]:
    """Return bundle member names, rejecting absolute or ``..`` (zip-slip) entries."""
    members: list[str] = []
    for name in archive.namelist():
        if name.endswith("/"):
            continue
        if name == MANIFEST_NAME:
            continue
        if not name.startswith(f"{BUNDLE_PREFIX}/"):
            continue
        relative = name[len(BUNDLE_PREFIX) + 1:]
        target = (dest / relative).resolve()
        try:
            target.relative_to(dest.resolve())
        except ValueError as exc:
            raise ValueError(f"archive member escapes destination: {name}") from exc
        members.append(name)
    return members


def _read_manifest(archive: zipfile.ZipFile) -> dict:
    try:
        return json.loads(archive.read(MANIFEST_NAME))
    except KeyError:
        return {}


def _missing_catalog_assets(house_dir: Path) -> list[str]:
    """List house-relative asset references whose files are absent after import."""
    missing: list[str] = []
    catalogs = (
        (house_dir / "assets" / "placeables.json", ("model", "plan_svg"), "types"),
        (house_dir / "furniture" / "imports.json", ("mesh",), "types"),
    )
    for path, keys, collection in catalogs:
        if not path.exists():
            continue
        try:
            document = json.loads(path.read_text())
        except ValueError:
            missing.append(f"{path.name} (unreadable)")
            continue
        for record in document.get(collection, []) or []:
            for key in keys:
                reference = record.get(key)
                if reference and not (house_dir / reference).is_file():
                    missing.append(reference)
    return missing


def import_house(archive_path: Path, dest_dir: Path, *, force: bool = False) -> ImportResult:
    """Unpack a house bundle into ``dest_dir`` and verify its relinked references.

    ``dest_dir`` must be empty or absent unless ``force`` is set.  Returns the missing-reference
    report so a caller can surface a broken import instead of a half-usable house.
    """
    archive_path = archive_path.resolve()
    if not archive_path.is_file():
        raise ValueError(f"archive not found: {archive_path}")
    dest_dir = dest_dir.resolve()
    if dest_dir.exists() and any(dest_dir.iterdir()) and not force:
        raise ValueError(f"destination is not empty (use force to overwrite): {dest_dir}")
    dest_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(archive_path) as archive:
        manifest = _read_manifest(archive)
        members = _safe_members(archive, dest_dir)
        if not members:
            raise ValueError("archive contains no house bundle (missing house/ prefix)")
        for name in members:
            relative = name[len(BUNDLE_PREFIX) + 1:]
            target = dest_dir / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(name) as source, open(target, "wb") as handle:
                shutil.copyfileobj(source, handle)

    name = str(manifest.get("name") or dest_dir.name)
    missing_underlays = tuple(_missing_relinked_underlays(dest_dir))
    missing_assets = tuple(_missing_catalog_assets(dest_dir))
    return ImportResult(house_dir=dest_dir, name=name,
                        missing_underlays=missing_underlays, missing_assets=missing_assets)


def _missing_relinked_underlays(house_dir: Path) -> list[str]:
    preferences = house_dir / "preferences.toml"
    if not preferences.exists():
        return []
    missing: list[str] = []
    for raw in _underlay_paths(preferences.read_text()):
        # Confirm every underlay the imported house declares resolves on disk. Bundled
        # underlays are now house-local; a still-external path here means it was not bundled.
        if not (house_dir / raw).is_file():
            missing.append(raw)
    return missing
