"""Regenerate ``ui/src/generated/sweepParity.json`` — the Python/TS sweep-kernel fixture.

``resolve/sweep.py`` and ``ui/src/three/tubeGeometry.ts`` are the same geometry written
twice, and a run that mitres differently in the viewer than in the glTF/IFC export is a bug
nobody would see until it was in a file. This writes the cases and Python's answer for each;
``tests/test_sweep_kernel.py`` asserts the file is current and
``ui/src/three/tubeGeometry.test.ts`` asserts TS reproduces it.

    .venv/bin/python scripts/gen_sweep_parity.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "packages" / "engine" / "src"))

from typehaus.resolve.model import SolidSweep  # noqa: E402
from typehaus.resolve.sweep import rect_profile, round_profile, sweep_legs  # noqa: E402

FIXTURE = REPO_ROOT / "ui" / "src" / "generated" / "sweepParity.json"

#: One case per shape the mitre has to get right, plus the two degenerate inputs that used to
#: be special cases in the band-stack code.
CASES = [
    ("straight-rect", [(0.0, 0.0, 0.0), (4.0, 0.0, 0.0)], rect_profile(0.1, 0.2)),
    ("raked-rect", [(0.0, 0.0, 0.0), (3.0, 0.0, 2.0)], rect_profile(0.0381, 0.0381)),
    ("plan-45-rect", [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (2.0, 1.0, 0.0)],
     rect_profile(0.05, 0.05)),
    ("plan-90-butt-round8", [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (1.0, 1.0, 0.0)],
     round_profile(0.019, 8)),
    ("vertical-then-horizontal-round12",
     [(0.0, 0.0, 0.0), (0.0, 0.0, -2.0), (2.0, 0.0, -2.05)], round_profile(0.0508, 12)),
    ("doubling-back", [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.02, 0.05, 0.0)],
     round_profile(0.0254, 12)),
    ("degenerate-repeat", [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (1.0, 0.0, 0.0),
                           (1.0, 1.0, -0.01)], round_profile(0.0254, 12)),
    ("near-collinear-rake", [(0.0, 0.0, 0.0), (1.0, 0.0, 0.003), (2.0, 0.0, 0.006)],
     rect_profile(0.0381, 0.0381)),
]


def payload() -> dict:
    cases = []
    for name, path, profile in CASES:
        sweep = SolidSweep(path=tuple(path), profile=profile)
        cases.append({
            "name": name,
            "path": [list(point) for point in path],
            "profile": [list(point) for point in profile],
            "legs": [[[[round(v, 12) for v in point] for point in ring] for ring in leg]
                     for leg in sweep_legs(sweep)],
        })
    return {"note": "generated by scripts/gen_sweep_parity.py — do not hand-edit",
            "cases": cases}


if __name__ == "__main__":
    FIXTURE.write_text(json.dumps(payload(), indent=2) + "\n")
    print(f"wrote {FIXTURE.relative_to(REPO_ROOT)}")
